/**
 * json-to-seed — read any curated static JSON under public/data/ and emit
 * SQL INSERT statements suitable for concatenation into
 * supabase/migrations/0002_seed.sql.
 *
 * Usage:
 *   npx tsx scripts/json-to-seed.ts > /tmp/nafas-seed-inserts.sql
 *
 * Currently handles:
 *   public/data/sensors.json       (array of sensor objects with lat/lon, so2, pm25, ...)
 *   public/data/oracle-zones.geojson (FeatureCollection of proposed zones)
 *   public/data/districts.geojson   (FeatureCollection of named districts)
 *
 * If a file is missing, it logs to stderr and skips that section.
 * The output is idempotent-friendly (ON CONFLICT DO NOTHING where possible).
 */

import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const DATA = join(ROOT, "public", "data");
const ORG_ID = "00000000-0000-0000-0000-0000000000a1";

type SensorJson = {
  id?: number;
  code?: string;
  name?: string;
  lat: number;
  lon: number;
  so2?: number;
  pm25?: number;
  district?: string;
  category?: string;
};

function escape(s: string | null | undefined): string {
  if (s == null) return "NULL";
  return `'${String(s).replace(/'/g, "''")}'`;
}

function jsonLit(v: unknown): string {
  return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
}

function fatal(msg: string): void {
  // stderr (so stdout stays clean for piping into psql)
  process.stderr.write(msg + "\n");
}

function emit(sql: string): void {
  process.stdout.write(sql + "\n");
}

function main(): void {
  const sensorsPath = join(DATA, "sensors.json");
  const oracleZonesPath = join(DATA, "oracle-zones.geojson");
  const districtsPath = join(DATA, "districts.geojson");

  emit(`-- Generated by scripts/json-to-seed.ts on ${new Date().toISOString()}`);
  emit("-- Run: npx tsx scripts/json-to-seed.ts > /tmp/nafas-seed-inserts.sql");
  emit("-- Then append to 0002_seed.sql if you want the curated JSON seeded.");
  emit("");

  // ---- Sensors ----
  if (existsSync(sensorsPath)) {
    const sensors = JSON.parse(readFileSync(sensorsPath, "utf8")) as SensorJson[];
    emit("-- ---- Sensors (from public/data/sensors.json) -------------------");
    for (const s of sensors) {
      const baseline = Math.max(5, Math.round((s.so2 ?? 0) * 0.12));
      const meta = {
        baseline,
        diurnal_peak: "dawn",
        source_json_id: s.id,
        district: s.district,
        category: s.category,
      };
      emit(
        `INSERT INTO sensors (org_id, location, type, unit, label, thresholds, metadata) VALUES (` +
          `${escape(ORG_ID)}, ` +
          `ST_GeogFromText('SRID=4326;POINT(${s.lon} ${s.lat})'), ` +
          `'so2', 'µg/m³', ${escape(s.name ?? s.code ?? `Sensor ${s.id}`)}, ` +
          `'{"warning":100,"critical":300}'::jsonb, ` +
          `${jsonLit(meta)}` +
          `) ON CONFLICT DO NOTHING;`,
      );
    }
    emit("");
  } else {
    fatal(`skip: ${sensorsPath} not found`);
  }

  // ---- Oracle zones ----
  if (existsSync(oracleZonesPath)) {
    const gj = JSON.parse(readFileSync(oracleZonesPath, "utf8")) as {
      features: Array<{
        type: "Feature";
        geometry: { type: string; coordinates: unknown };
        properties?: Record<string, unknown>;
      }>;
    };
    emit("-- ---- Oracle zones (from public/data/oracle-zones.geojson) -----");
    for (const f of gj.features ?? []) {
      if (f.geometry?.type !== "Polygon") continue;
      const name = (f.properties?.name as string) ?? "Zone ORACLE";
      const kind = (f.properties?.kind as string) ?? "marine_protected";
      const slug = (f.properties?.slug as string) ?? slugify(name);
      const wkt = polygonToWkt(f.geometry.coordinates as number[][][]);
      emit(
        `INSERT INTO zones (org_id, kind, name, slug, geometry, metadata) VALUES (` +
          `${escape(ORG_ID)}, ` +
          `${escape(kind)}, ${escape(name)}, ${escape(slug)}, ` +
          `ST_GeogFromText('SRID=4326;${wkt}'), ` +
          `${jsonLit(f.properties ?? {})}` +
          `) ON CONFLICT DO NOTHING;`,
      );
    }
    emit("");
  } else {
    fatal(`skip: ${oracleZonesPath} not found`);
  }

  // ---- Districts ----
  if (existsSync(districtsPath)) {
    const gj = JSON.parse(readFileSync(districtsPath, "utf8")) as {
      features: Array<{
        type: "Feature";
        geometry: { type: string; coordinates: unknown };
        properties?: Record<string, unknown>;
      }>;
    };
    emit("-- ---- Districts (from public/data/districts.geojson) -----------");
    for (const f of gj.features ?? []) {
      if (f.geometry?.type !== "Polygon") continue;
      const name = (f.properties?.name as string) ?? "Quartier";
      const wkt = polygonToWkt(f.geometry.coordinates as number[][][]);
      emit(
        `INSERT INTO zones (org_id, kind, name, slug, geometry, metadata) VALUES (` +
          `${escape(ORG_ID)}, ` +
          `'residential', ${escape(name)}, ${escape(slugify(name))}, ` +
          `ST_GeogFromText('SRID=4326;${wkt}'), ` +
          `${jsonLit(f.properties ?? {})}` +
          `) ON CONFLICT DO NOTHING;`,
      );
    }
    emit("");
  } else {
    fatal(`skip: ${districtsPath} not found`);
  }

  if (
    !existsSync(sensorsPath) &&
    !existsSync(oracleZonesPath) &&
    !existsSync(districtsPath)
  ) {
    fatal(
      "No curated JSON files found under public/data/. Nothing to emit.\n" +
        "Supported: sensors.json, oracle-zones.geojson, districts.geojson",
    );
  }
}

function polygonToWkt(rings: number[][][]): string {
  const parts = rings.map(
    (ring) =>
      `(${ring.map(([x, y]) => `${x} ${y}`).join(", ")})`,
  );
  return `POLYGON ${parts.join(", ")}`.replace("POLYGON (", "POLYGON(");
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

main();
